In [1]:
import yfinance as yf

In [2]:
df = yf.download("GC=F", start="2019-01-01", end="2025-10-01", auto_adjust=True)
df.columns = [col[0] for col in df.columns]

[*********************100%***********************]  1 of 1 completed

In [3]:
df

                  Close         High          Low         Open  Volume
Date
2019-01-02  1281.000000  1286.000000  1277.599976  1286.000000     149
2019-01-03  1291.800049  1292.000000  1286.699951  1286.800049      10
2019-01-04  1282.699951  1294.199951  1275.300049  1294.199951      34
2019-01-07  1286.800049  1286.800049  1286.599976  1286.800049       2
2019-01-08  1283.199951  1283.199951  1278.199951  1280.500000      54
...                 ...          ...          ...          ...     ...
2025-09-24  3732.100098  3772.500000  3732.100098  3769.800049     588
2025-09-25  3736.899902  3756.000000  3724.699951  3742.800049    1899
2025-09-26  3775.300049  3775.300049  3775.300049  3775.300049   19308
2025-09-29  3820.899902  3827.600098  3754.800049  3754.800049    8860
2025-09-30  3840.800049  3865.500000  3793.399902  3827.500000    1611

[1698 rows x 5 columns]

In [4]:
df.to_csv("../data/gold_prices.csv")